### ISSUE TITLE
Generate exe/DLL is flagged by Defender

### ISSUE THREAD

**Issue by egotisticalgiraffe** [HavocFramework/Havoc#147]
The exe generated by Havok is detected by Windows Defender. I used the default settings to generate the exe, which was delivered via download (Edge).

![image](https://user-images.githubusercontent.com/39986163/194610588-9ceed138-6da3-48d9-90be-7c749603ee00.png)

(I allowed it to test callbacks, which worked)

**Comment by chbGSmCm** [comment]
This will inevitably happen to any opensource project. However this is very interesting, as it detects `Wacatac` as a true negative.

**Comment by egotisticalgiraffe** [comment]
True. I added this at the request of one of the devs, for info.

**Comment by InfosecWestwood6969** [comment]
> This will inevitably happen to any opensource project. However this is very interesting, as it detects `Wacatac` (and not Havoc).

You wont see havoc coz its a generic detection and ms is not botherd to build detectns as it is detectd with generic yaras... lol

**Comment by T1Cr4azy** [comment]
Just use a Crypter :(

**Comment by the2dl** [comment]
You need to strip apart the default teamserver config, make sure things like X-Havoc aren't there. If you run strings on a default payload you can see all the easy stuff vendors built detections on. There are some other areas Yara rules can be built on the payloads as well, but I'm still able to bypass defender by making sure I don't run the default config.

Over time detections from vendors will get better, but right now they must be basing it on some default config options like X-Havoc, Chrome version UA string, various other easily identifiable strings and probably exact filesize of 58kb every time.

Also for the exe\dll versions, the framework generates a static string at the bottom exactly 10 characters long Aa-Zz+1-9.exe, so some regex in a Yara rule will catch that as well.

**Comment by Elon-Sarif** [comment]
> Just use a Crypter :(

can u give us a good reference for a crypter? thanks mate

**Comment by iNoSec2** [comment]
Script kiddies are in the place...

**Comment by iNoSec2** [comment]
> 

Not talking about you ;) More about crypter boys...

**Comment by Elon-Sarif** [comment]
> > 
> 
> Not talking about you ;) More about crypter boys...

What's wrong with crypter, maybe you can share with us so we can all improve ? 🙂

**Comment by assume-breach** [comment]
Delete your Defender logs through Event Viewer, change the name of your exe and try again. It hasn't been signatured yet and still gets past Defender for Endpoint.

**Comment by sempervictus** [comment]
This project in a neat effort, but _this_ particular issue is a cat-n-mouse game you won't solve in the public domain. Over the years i've removed all sorts of static IOCs from meterpreter, from our comms streams, etc, and even back _then_ the "valiant defender" miscreants just pulled our sources and updated their sigs (check out how TLVCrypt came to be - fun times).
Crypters, packers, post-product obfuscators... these are not the tools of a Jedi since they're clumsy like blasters and have to have various known semantics of entrypoint and underlying code access to work without sources, compile and link-time access to the plumbing, and ability to resolve symbols before stripping happens to target relevant call/jump/pivot sites.
In order to not have sufficient segments known "to be bad" close enough to each other in the executed/buffered/EDR-callback-processed data, the changes have to be made before/during build-time and neither the inputs nor outputs should be fully public code as that _will_ produce predictable instruction sets and heuristics (short of something like GCC plugins to mangle those every time) will find them once your payload is somebody's sample. Runtime trickery such as unmapping, stack mangling, code-caving, etc help but first you have to get through the on-load/on-execution callback traps in ring0 which will analyze the contents of what you're writing into and executing from memory. Not going to give any pointers to relevant tooling - this discipline requires many thousands of hours of research; but will reiterate that when it comes to the top of the spear, it cannot come straight off the shelf in serious engagements.

**Comment by sempervictus** [comment]
@Elon-Sarif agreed, though you can break up what you keep private in various ways. I do have some private stager shellcode, but mostly its the modified obfuscators that give me an edge at initial execution. Payload _runtimes_ are kind of key since the modular ones all pivot off that for their central dispatch - complex enough to obfuscate, but then the entrypoints to those obfu segments become of interest to EDR. The more modular, less present when not being executed, and more malleable in its relevant context the subsystem is; the more points of inflection for variation and evasion.
