### ISSUE TITLE
Write C# GUI instead of QT

### ISSUE THREAD

**Issue by InfosecWestwood6969** [HavocFramework/Havoc#200]
### Contact Details

infosecwestwood6969@gmail.com

### What happened?

QT is a pain to install on Gentoo or Arch. I ended up installing qtcreator full package to install the qt client but was very painful. Writing a C# application can handle things much better as lot of people use Windows instd of linux, even Cobaltstrike has it.

### Did You Do a Pull First?

Latest (You performed a pull first)

### Relevant log output

```shell
NA
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Hey, thank you so much for opening this issue. I am super happy to rewrite 10k+ of C++ code into another language that I am not familiar with so that a random person on the internet can install it easily or because it's a "pain in the ass" to install it. You can pay me a lot of money to do so or else please don't use it. Thank you.

**Comment by InfosecWestwood6969** [comment]
It should be usable for you to say "don't use it". How can I use something that does not work. Half the things keep crashing every few minutes and it is the most unstable piece of shit I've used. I only tried it against Sliver because of the hype you created in your discord channel and on twitter. A 10 year old rat sold on sinister.ly is better than this garbage. Fuck you.

**Comment by InfosecWestwood6969** [comment]
And why do you keep asking money for everything. No one asked you to write this software. If you actually wrote something that worked, I would even consider paying a few pennies...

**Comment by raf181** [comment]
why the fuck you guys fighting for a free project isn't the whole purpose of GitHub to collaborate if you want something get the code you need and make it yourself.

**Comment by InfosecWestwood6969** [comment]
I asked him politely about the issue. He asked money with so money ego as if give me money or do it on your own. He needs some humility, or else he will keep asking money like a begger. If he wants money, go and earn instead of asking it to people on internet.

**Comment by Cracked5pider** [comment]
You asked me to rewrite the client in C# lmao. Do you have any idea how much time this would cost? I am doing this in my free time and for fun. You don't need to use it and I am happy if someone reports issues with a detailed explanation of how it crashed with screenshots/logs. You just open issues and say "it's crashing" and that's it without more info. 
And I if really wanted to make money I would have sold it like other C2s are doing but I wanted other people to learn from it.

**Comment by InfosecWestwood6969** [comment]
I opened and explained the issues to you already. I said how the agent does not connect back if the server is killed and started again. the killing of server can be manual or due to crashes as there is not a lot of command input validation like the -1 bug in sleep. I am doing a favor by reporting the issues for you. if you don't like it, not my problem. there are a lot of open source c2s which actually work. No one will pay for this crap either way

**Comment by Cracked5pider** [comment]
You are talking about this #199 issue. Which I am currently investigating and going to fix. <br>
In this issue where we are currently talking is something I can't do since I don't know C# and you are asking me to rewrite 10k+ lines of C++ code just because it fails to parse some commands (which I am fully aware of and going to fix just give me some time). Look I am not getting paid for this and I am happy if someone is reporting issues/bugs but you just complained and started to insult my project and calling it shit after I refused to rewrite the C2 in C#. If you know more then go and write your own C2. You straight up started to call my project shit after I told you that it's still in early development and not even a month out so what do you expect? being bug free without any issues?  <br>
And I am sorry for being a little bit aggressive in my previous messages but you need to understand that I don't have that much free time and I am trying my best to make it as stable as possible. 
So It would help me more if you could provide more information on how the issue occurred with reproducible steps (maybe some screenshots).

**Comment by CodeXTF2** [comment]
> I asked him politely about the issue. He asked money with so money ego as if give me money or do it on your own. He needs some humility, or else he will keep asking money like a begger. If he wants money, go and earn instead of asking it to people on internet.

i think the part about money was a rhetorical question. point being he doesnt feel like rewriting half the codebase and he isnt obligated to do so.

oh, and do yourself a favour and do your pentesting/redteaming on a linux VM like everyone else.

**Comment by cbedhoam620** [comment]
> 您[＃199](https://github.com/HavocFramework/Havoc/issues/199)问题这个。我目前正在正在准备准备修复修复修复。。我们正在正在正在讨论讨论讨论讨论的的的的这个的的这个的这个的的这个 问题正在我们目前我们目前目前我们我们我们我们我们我们我们我们这个目前我们我们这个这个这个目前这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个这个无法解析命令完全完全并要要是是给（（而且在我拒绝使用C#重写C2后称它为狗屎。如果你知道更多，那就去写你自己的C2。在我告诉你它仍然处在早期开发阶段甚至你吽还不到一个，就直截称我的为为，所以所以为你期望什么？没有没有没有任何任何问题问题问题问题没有？错误？？ 我我我很很抱歉抱歉在在我之前之前之前的消息消息消息消息最大的努力让它尽可能地稳定。 因此，如果您能提供更多有关问题如何通过可重新发现的步骤（可能是一些屏幕截图）发出的信息，那我将有専。

Yes, I support you.  He just wants to play for free.  He wants people to work for him for free. Don't worry about him.  Qt is fine.  If there's a problem, just fix it.  We don't need a bunch of interpreter languages

**Comment by cbedhoam620** [comment]
> You are talking about this #199 issue. Which I am currently investigating and going to fix. In this issue where we are currently talking is something I can't do since I don't know C# and you are asking me to rewrite 10k+ lines of C++ code just because it fails to parse some commands (which I am fully aware of and going to fix just give me some time). Look I am not getting paid for this and I am happy if someone is reporting issues/bugs but you just complained and started to insult my project and calling it shit after I refused to rewrite the C2 in C#. If you know more then go and write your own C2. You straight up started to call my project shit after I told you that it's still in early development and not even a month out so what do you expect? being bug free without any issues? And I am sorry for being a little bit aggressive in my previous messages but you need to understand that I don't have that much free time and I am trying my best to make it as stable as possible. So It would help me more if you could provide more information on how the issue occurred with reproducible steps (maybe some screenshots).

Yes, I support you. He just wants to play for free. He wants people to work for him for free. Don't worry about him. Qt is fine. If there's a problem, just fix it. We don't need a bunch of interpreter languages

**Comment by winterrdog** [comment]
@Cracked5pider just keep doing what you're doing we already like it😍. 

When you're rising, Haters keep on rising. 🤝
Which indirectly means you're becoming bada55😎😈😈

Keep at it 💪

**Comment by SecT0uch** [comment]
C# please tell me this is a joke :rofl:
