### ISSUE TITLE
[File a bug report for the Demon Implant]: Weird bug, upon opening the Process List the Demon implant freezes/becomes unresponsive

### ISSUE THREAD

**Issue by Wagon2781** [HavocFramework/Havoc#331]
### What happened?

Weird bug, upon opening the Process List the Demon implant freezes/becomes unresponsive

Process is still running on my vm, using 10% cpu which is kinda crazy but whatever
(Seriously, what the hell is it doing to be using 10% cpu... firefox uses 0.1%...?)

Has to be task manager closed and reran

Why is this?

### Did You Do a Pull First?

Anything else (You didn't pull...)

### Did You Try With the Dev Branch?

No (You only tried the main branch...)

### Relevant log output

```shell
No logs regarding this issue I think
```

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
Hey thanks for reporting this. 
I was aware of this issue and it already has been fixed in the dev branch. 
This issue is because I made a silly mistake when it comes to opening a process handle and looping through the snapshot in [this line of code](https://github.com/HavocFramework/Havoc/blob/main/payloads/Demon/Source/Core/Command.c#L602). When it failed to open a process handle it tries to go to the next process by continuing the loop. Tho it did not increase the offset of the snapshot so it stayed at the same process trying to open the same process over and over again for all eternity.  
This issue has been fixed & resolved in the dev branch. Please check it out.
