### ISSUE TITLE
[C2 over WAN]: NGROK

### ISSUE THREAD

**Issue by rfarah21** [HavocFramework/Havoc#427]
### What happened?

Not a bug specifically. Maybe I got something wrong. I am trying to use this over WAN since we may have an engagement soon and want to explore a new C2. For the life of me I am unable to get this to work with ngrok. Any screenshots or explanations would be appreciated. Steps taken are below:

1 - Setup the havoc teamserver and created a user in the profiles/havoc config gile
2 - Setup ngrok on 2 ports. One mapped to where you logon to the team server and the other mapped to the c2 listening port
3 - Created a listener (this is where I suspect I am doing something wrong)

![Screenshot from 2023-10-25 19-15-04](https://github.com/HavocFramework/Havoc/assets/98347396/15fd3799-6d33-4d35-9b4a-6a3e02ddc0bd)

4 - Created a payload from the listener and ran it on a Windows machine with defender disabled. 
Result: Radio Silence but the process is running

Expected behavior:
Get a callback.

Potential solution:
Add the ngrok proxy settings in the enable proxy section ? I tried that and still radio silence ? Typo maybe ?

### Did You Try With the Dev Branch?

No (You only tried the main branch...)

### Did You Read Over Your Issue First?

- [X] I declare I made an effort and provided the necessary information for replication of the issue.

**Comment by Cracked5pider** [comment]
the teamserver should be used on a public VPS (and obv behind a redirector). It's why the teamserver and client are two separate binaries (you can read more about this [here](https://havocframework.com/docs/welcome))
It does not officially support it nor do I have planned on making it truly work with NGROK because of a lot of "script kiddies" use it. I close this issue for now.
